<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d143a153-c79d-42b1-87cf-136366562d10</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-backpack</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-backpack') and equals(@name,'remove-sauce-labs-backpack') and equals(@class,'btn btn_secondary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory</value>
        <webElementGuid>253e9e6d-f0ba-4316-94c4-e2be0dd1e618</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>c9829a26-266e-4107-9d8b-5ab7ed99a6ae</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>7cbd31d1-f5c3-4b4c-9c8a-88b15720b0b1</webElementGuid>
    </webElementProperties>
</WebElementEntity>