<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f182ee0d-e31f-491e-937e-d62228fadb0e</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.inventory_details_name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'inventory_details_name large_size')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>inventory_details_name large_size</value>
        <webElementGuid>5ae88022-a38c-4518-a924-d8eea36b91ca</webElementGuid>
    </webElementProperties>
</WebElementEntity>