<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa96a28c-07a8-4c43-a40a-8cf4f0510bc9</elementGuidId>
    <imagePath></imagePath>
    <name>button_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[9]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#finish</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'finish') and equals(@name,'finish') and equals(@class,'btn btn_action btn_medium cart_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium cart_button</value>
        <webElementGuid>e62cc190-5a91-43fa-a35b-abbbbe32db6e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>fc9c9d8c-f75d-4907-968a-2dd603cd9958</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>3923a8e5-1401-4bbc-ae8a-cf89f7497ff1</webElementGuid>
    </webElementProperties>
</WebElementEntity>